### ISSUE TITLE
Can't build with latest buildroot (2020.11.1)

### ISSUE THREAD

**Issue by JustZhenya** [unframework/licheepi-nano-buildroot#4]
First error I get is:
`/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of 'yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here`

After commenting `YYLTYPE yylloc;` in `output/build/uboot-nano-v2018.01/scripts/dtc/dtc-lexer.lex.c` I get new error:
`Error: arch/arm/dts/.suniv-f1c100s-licheepi-nano.dtb.pre.tmp:59.1-10 syntax error`

And now I don't know how to fix it.
59-th line in this file is:
`\#include "sunxi-u-boot.dtsi"`

Any ideas?

**Comment by unframework** [comment]
Thanks for the report, looks pretty unfamiliar to me! Maybe the device tree definitions were updated since I last did my checkout and compilation...

I will be getting back to this project in a few weeks, so I will fix any new issues that come up then, but meanwhile I can't help much unfortunately, since I am not experienced with inner kernel workings.

**Comment by Mr-Bossman** [comment]
the second one i have not figued out but it works on older systems. although u can look at the commit to my build root and linux repos it has u just have to put extern infront `YYLTYPE yylloc;`

**Comment by Mr-Bossman** [comment]
the second line is freaky cus the device tree never metions it the only thing referancing it it in the defconfig. personaly i just used the one i compiled in 2020. but it would be intersing to know why it happens on newer distros what distro are u using what device tree compiler and what gcc i used gcc 10 and dtc of 1.6 im using debian sid

**Comment by unframework** [comment]
Just to add some more context for the extern fix suggested above, this seems to be a general Buildroot compilation issue on some Linux versions. One discussion link that I found: https://www.reddit.com/r/LineageOS/comments/hkq8ah/multiple_definitions_error_in_dtc_tool_when/

Because I am using Ubuntu inside Vagrant on my local machine, I can't reproduce this issue unfortunately (tried to do it today). The toolchain `gcc` that is built by Buildroot is version 8 in my config. The host `gcc` inside my Vagrant is even older: v7.5.0.

In general, I would look at the upstream Buildroot bug reports for this for more info. Since this is not specific to Lichee Pi Nano, I am closing this thread for now, but feel free to reopen if more issues happen!
